"""initial schema: spawning_sites and escapement_observations

Revision ID: 92a296d92ff4
Revises: 
Create Date: 2026-02-28 14:22:35.091624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '92a296d92ff4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spawning_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nuseds_pop_id', sa.Integer(), nullable=True),
    sa.Column('stream_name', sa.Text(), nullable=True),
    sa.Column('waterbody', sa.Text(), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('watershed_code', sa.Text(), nullable=True),
    sa.Column('conservation_unit', sa.Text(), nullable=True),
    sa.Column('cu_status', sa.String(length=20), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spawning_sites_geom', 'spawning_sites', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spawning_sites_nuseds_pop_id'), 'spawning_sites', ['nuseds_pop_id'], unique=True)
    op.create_index(op.f('ix_spawning_sites_species'), 'spawning_sites', ['species'], unique=False)
    op.create_table('escapement_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('natural_adult_spawners', sa.Integer(), nullable=True),
    sa.Column('natural_jack_spawners', sa.Integer(), nullable=True),
    sa.Column('total_spawners', sa.Integer(), nullable=True),
    sa.Column('adult_broodstock_removals', sa.Integer(), nullable=True),
    sa.Column('total_return_to_river', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.String(length=50), nullable=True),
    sa.Column('run_type', sa.String(length=50), nullable=True),
    sa.Column('survey_method', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['spawning_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_escapement_site_year', 'escapement_observations', ['site_id', 'year'], unique=False)
    op.create_index('ix_escapement_species_year', 'escapement_observations', ['species', 'year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_escapement_species_year', table_name='escapement_observations')
    op.drop_index('ix_escapement_site_year', table_name='escapement_observations')
    op.drop_table('escapement_observations')
    op.drop_index(op.f('ix_spawning_sites_species'), table_name='spawning_sites')
    op.drop_index(op.f('ix_spawning_sites_nuseds_pop_id'), table_name='spawning_sites')
    op.drop_index('ix_spawning_sites_geom', table_name='spawning_sites', postgresql_using='gist')
    op.drop_table('spawning_sites')
    # ### end Alembic commands ###
